### ISSUE TITLE
YML expression lang

### ISSUE THREAD

**Issue by norkunas** [rosstuck/TuckConverterBundle#12]
This converter throws a conversion error when converting from yml to xml if yml is configured in this way with expression language:

```
services:
    service_name:
        arguments:
           - "@=container.has('serializer') ? service('serializer') : null"
```
