### ISSUE TITLE
Abstract and Parent aren't supported

### ISSUE THREAD

**Issue by philippecarle** [rosstuck/TuckConverterBundle#15]
I'll try to create a PR in the next days, but just to warn every developers using this SO useful bundle (I just migrated a whole project to xml, it saved my life) :
abstract: true and parent:… are not supported and won't be converted

A routing converter would be great too, I wrote something which was ok for my use, but it'd worth to be shared and optimized.

Once again, thx !

**Comment by rosstuck** [comment]
Hmm, this bundle is based on the actual Symfony converters and dumpers so they should be supported.

Are the parent definitions in the same file you're importing? Just curious.

**Comment by philippecarle** [comment]
Yes they are. Here is the example :

```
    my_project.jms_repository:
        class: Vendor\Segment\MyBundle\Repository\JMSRepository
        abstract: true
        calls:
            - [ setSerializer, [ @jms_serializer ] ]
    my_project.my_repository:
        class: Vendor\Segment\MyBundle\Repository\MyRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - "MyBundle:MyEntity"
        parent:
            my_project.jms_repository
```
